//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class baja
    {
        public int idBaja { get; set; }
        public string descripcion { get; set; }
        public string fecha { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idCorteCaja { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual cortecaja cortecaja { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ingrediente ingrediente { get; set; }
        public virtual producto producto { get; set; }
    }
}
