//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.direccioncliente = new HashSet<direccioncliente>();
            this.pedidocliente = new HashSet<pedidocliente>();
        }
    
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idTelefono { get; set; }
    
        public virtual telefono telefono { get; set; }
        public virtual ICollection<direccioncliente> direccioncliente { get; set; }
        public virtual ICollection<pedidocliente> pedidocliente { get; set; }
    }
}
