//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.direccion = new HashSet<direccion>();
            this.pedidodomicilio = new HashSet<pedidodomicilio>();
        }
    
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<int> telefono { get; set; }
    
        public virtual ICollection<direccion> direccion { get; set; }
        public virtual ICollection<pedidodomicilio> pedidodomicilio { get; set; }
    }
}
