//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class cortecaja
    {
        public cortecaja()
        {
            this.baja = new HashSet<baja>();
            this.entradaextraordinaria = new HashSet<salidaextraordinaria>();
            this.pedido = new HashSet<pedido>();
            this.salidaextraordinaria = new HashSet<salidaextraordinaria>();
        }
    
        public int idCorteCaja { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string fecha { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual ICollection<baja> baja { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<salidaextraordinaria> entradaextraordinaria { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<salidaextraordinaria> salidaextraordinaria { get; set; }
    }
}
