//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccioncliente
    {
        public int idClienteDireccion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idDireccion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual direccion direccion { get; set; }
    }
}
