//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadopedido
    {
        public estadopedido()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int idEstadoPedido { get; set; }
        public string nombreEstado { get; set; }
    
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
