//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public inventario()
        {
            this.ingrediente = new HashSet<ingrediente>();
            this.producto = new HashSet<producto>();
        }
    
        public int idInventario { get; set; }
        public string ultimaActualizacion { get; set; }
    
        public virtual ICollection<ingrediente> ingrediente { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
