//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public inventario()
        {
            this.ingrediente = new HashSet<ingrediente>();
            this.producto = new HashSet<producto>();
        }
    
        public int idInventario { get; set; }
        public string ultimaActualizacion { get; set; }
    
        public virtual ICollection<ingrediente> ingrediente { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
