//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class italianpizzaEntities : DbContext
    {
        public italianpizzaEntities()
            : base("name=italianpizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<baja> baja { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cortecaja> cortecaja { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<direccioncliente> direccioncliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<entradaextraordinaria> entradaextraordinaria { get; set; }
        public virtual DbSet<estadopedido> estadopedido { get; set; }
        public virtual DbSet<ingrediente> ingrediente { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<medidaproducto> medidaproducto { get; set; }
        public virtual DbSet<mesa> mesa { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<pedidocliente> pedidocliente { get; set; }
        public virtual DbSet<pedidolocal> pedidolocal { get; set; }
        public virtual DbSet<pedidoproducto> pedidoproducto { get; set; }
        public virtual DbSet<pedidoproveedor> pedidoproveedor { get; set; }
        public virtual DbSet<pedidoproveedoringrediente> pedidoproveedoringrediente { get; set; }
        public virtual DbSet<pedidoproveedorproducto> pedidoproveedorproducto { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<receta> receta { get; set; }
        public virtual DbSet<recetaingrediente> recetaingrediente { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<salidaextraordinaria> salidaextraordinaria { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<tipoproducto> tipoproducto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
