//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class italianpizzaEntities : DbContext
    {
        public italianpizzaEntities()
            : base("name=italianpizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<baja> baja { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<cortecaja> cortecaja { get; set; }
        public DbSet<direccion> direccion { get; set; }
        public DbSet<direccioncliente> direccioncliente { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<entradaextraordinaria> entradaextraordinaria { get; set; }
        public DbSet<estadopedido> estadopedido { get; set; }
        public DbSet<ingrediente> ingrediente { get; set; }
        public DbSet<inventario> inventario { get; set; }
        public DbSet<medidaproducto> medidaproducto { get; set; }
        public DbSet<mesa> mesa { get; set; }
        public DbSet<pedido> pedido { get; set; }
        public DbSet<pedidocliente> pedidocliente { get; set; }
        public DbSet<pedidolocal> pedidolocal { get; set; }
        public DbSet<pedidoproducto> pedidoproducto { get; set; }
        public DbSet<pedidoproveedor> pedidoproveedor { get; set; }
        public DbSet<pedidoproveedoringrediente> pedidoproveedoringrediente { get; set; }
        public DbSet<pedidoproveedorproducto> pedidoproveedorproducto { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<receta> receta { get; set; }
        public DbSet<recetaingrediente> recetaingrediente { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<salidaextraordinaria> salidaextraordinaria { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<telefono> telefono { get; set; }
        public DbSet<tipoproducto> tipoproducto { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
