//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoproveedor
    {
        public pedidoproveedor()
        {
            this.pedidoproveedoringrediente = new HashSet<pedidoproveedoringrediente>();
            this.pedidoproveedorproducto = new HashSet<pedidoproveedorproducto>();
        }
    
        public int idPedidoProveedor { get; set; }
        public string fecha { get; set; }
        public byte[] monto { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public string estado { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual ICollection<pedidoproveedoringrediente> pedidoproveedoringrediente { get; set; }
        public virtual ICollection<pedidoproveedorproducto> pedidoproveedorproducto { get; set; }
    }
}
