//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.pedidoproducto = new HashSet<pedidoproducto>();
        }
    
        public int idPedido { get; set; }
        public string fecha { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> idCorteCaja { get; set; }
    
        public virtual cortecaja cortecaja { get; set; }
        public virtual pedidodomicilio pedidodomicilio { get; set; }
        public virtual pedidolocal pedidolocal { get; set; }
        public virtual ICollection<pedidoproducto> pedidoproducto { get; set; }
    }
}
