//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidolocal
    {
        public int idPedidoLocal { get; set; }
        public Nullable<int> idMesa { get; set; }
    
        public virtual mesa mesa { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
