//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.baja = new HashSet<baja>();
            this.pedidoproducto = new HashSet<pedidoproducto>();
            this.pedidoproveedorproducto = new HashSet<pedidoproveedorproducto>();
        }
    
        public int idProducto { get; set; }
        public string caducidad { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> codigo { get; set; }
        public string lote { get; set; }
        public string medida { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idInventario { get; set; }
        public Nullable<int> idReceta { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
        public Nullable<int> idMedidaProducto { get; set; }
    
        public virtual ICollection<baja> baja { get; set; }
        public virtual inventario inventario { get; set; }
        public virtual medidaproducto medidaproducto { get; set; }
        public virtual ICollection<pedidoproducto> pedidoproducto { get; set; }
        public virtual ICollection<pedidoproveedorproducto> pedidoproveedorproducto { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual receta receta { get; set; }
        public virtual tipoproducto tipoproducto { get; set; }
    }
}
