//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.ingrediente = new HashSet<ingrediente>();
            this.pedidoproveedor = new HashSet<pedidoproveedor>();
            this.producto = new HashSet<producto>();
        }
    
        public int idProveedor { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefono { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual ICollection<ingrediente> ingrediente { get; set; }
        public virtual ICollection<pedidoproveedor> pedidoproveedor { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
