//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class recetaingrediente
    {
        public int idRecetaIngrediente { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> idReceta { get; set; }
        public Nullable<int> idIngrediente { get; set; }
    
        public virtual ingrediente ingrediente { get; set; }
        public virtual receta receta { get; set; }
    }
}
