//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public receta()
        {
            this.producto = new HashSet<producto>();
            this.recetaingrediente = new HashSet<recetaingrediente>();
        }
    
        public int idReceta { get; set; }
        public Nullable<int> tiempoCoccion { get; set; }
        public string descripcion { get; set; }
        public string instrucciones { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<recetaingrediente> recetaingrediente { get; set; }
    }
}
