//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public receta()
        {
            this.producto = new HashSet<producto>();
            this.recetaingrediente = new HashSet<recetaingrediente>();
        }
    
        public int idReceta { get; set; }
        public Nullable<int> tiempoCoccion { get; set; }
        public string descripcion { get; set; }
        public string instrucciones { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<recetaingrediente> recetaingrediente { get; set; }
    }
}
