//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItalianPicza.DatabaseModel.DataBaseMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoproducto
    {
        public tipoproducto()
        {
            this.producto = new HashSet<producto>();
            this.proveedor = new HashSet<proveedor>();
        }
    
        public int idTipoProducto { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<proveedor> proveedor { get; set; }
    }
}
